name: icp-tenant-ui-cd-non-prod

on:
  workflow_dispatch: {}
  workflow_call: {}

concurrency:
  group: cd-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on:
      - ubuntu-latest


    strategy:
      fail-fast: true

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Print
      run: |
        echo "Running in Non Prod........"
