name: icp-tenant-ui

on:
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on:
      - ubuntu-latest


    strategy:
      fail-fast: true

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Print
      run: |
        echo "✅ Running CI checks for PR into main"
