name: icp-tenant-ui-non-prod

on:
  push:
    branches:
      - non-prod

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on:
      - ubuntu-latest

    strategy:
      fail-fast: true

    steps:
    - name: Print
      run: |
        echo "Building........"
  deploy:
    needs: build
    if: ${{ github.ref == 'refs/heads/non-prod' }}
    uses: ./.github/workflows/cd.yaml
