name: icp-tenant-ui-deploy

on:
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    if: github.actor == 'captainhawkeye1'
    runs-on:
      - ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Print
      run: |
        echo "Running in Main with correct Actor........"
