name: icp-tenant-ui-deploy

on:
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  user-validation:
    name: Validate GitHub Actor
    runs-on: ubuntu-latest
    outputs:
      authorized: ${{ steps.check.outputs.authorized }}
    steps:
      - id: check
        run: |
          ACTOR="${{ github.actor }}"
          ALLOWED='${{ vars.ALLOWED_ACTORS }}'

          if echo "$ALLOWED" | jq -e ". | index(\"$ACTOR\")" > /dev/null; then
            echo "✅ Authorized user: $ACTOR"
            echo "authorized=true" >> "$GITHUB_OUTPUT"
          else
            echo "❌ Unauthorized user: $ACTOR"
            echo "authorized=false" >> "$GITHUB_OUTPUT"
          fi

  deploy:
    needs: user-validation
    if: needs.user-validation.outputs.authorized == 'true'
    runs-on:
      - ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Print
      run: |
        echo "Running in Main with correct Actor........"
