name: icp-tenant-ui-deploy

on:
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  ALLOWED_ACTORS: '["captainhawkeye1", "user2", "user3"]'

jobs:
  deploy:
    if: contains(fromJson(vars.ALLOWED_ACTORS), github.actor)
    runs-on:
      - ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Print
      run: |
        echo "Running in Main with correct Actor........"

  unauthorized:
    name: Not Authorized
    runs-on: ubuntu-latest
    if: >
      !contains(fromJson(vars.ALLOWED_ACTORS), github.actor)

    steps:
      - run: echo "❌ You are not authorized to deploy to Production."
