name: icp-orchestrator

on:
  push:
    branches:
      - pre-main
  workflow_dispatch: {}

permissions:
  contents: read
  id-token: write

jobs:
  run-ci:
    uses: ./.github/workflows/ci.yaml

  run-cd:
    needs: run-ci
    uses: ./.github/workflows/cd.yaml
